### ISSUE TITLE
For updation of skill section.

### ISSUE THREAD

**Issue by vivekrawat21** [vivekrawat21/Personal-Portfolio#2]
I am raising this issue for updation of my skill section if anybody know html , css and js please create a skill section for portfolio as per my github profile .
For that fork my repo and  create your branch and update the skill section then create pull req.

**Comment by enlguy** [comment]
So you're asking other people to put their skills into your portfolio skills section????  Sounds highly unethical.

Also, "updation" is not a word.

**Comment by vivekrawat21** [comment]
Thanks for suggestion and sorry for inconvenience ,i am newby here  i'll close this issue asap

**Comment by vivekrawat21** [comment]
Closed
